### ISSUE TITLE
Dropdown item replaces the title after click in top bar

### ISSUE THREAD

**Issue by max-ostapenko** [vitaluha/londonmeasurecampboard#2]
After clicking on the dropdown item in sponsors' menu, for example, the name of the sponsor replaces the title of the dropdown -"Sponsors".
Same behaviour in another dropdown.
https://measurecampboard.herokuapp.com/2020?city=Europe

**Comment by vitaluha** [comment]
@max-ostapenko Thanks, will take a look.

**Comment by vitaluha** [comment]
@max-ostapenko Fixed. Now it acts as menu - you click dropdown item, then it expands. Main item no longer being replaced.

**Comment by max-ostapenko** [comment]
Looking good! Thanks.
